language: ruby
sudo: false
rvm:
- 2.1
script:
- bundle exec jekyll build
- bundle exec htmlproofer ./_site --only-4xx --check-html --url-ignore "/example.com/"
env:
global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
