# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Igor Moiseev
tagline:             'ApplMath, Developer'
description:         'Some notes about MySQL and PostgreSQL. Ceph''s Storage clustering and KVM virtualization. Programming with NodeJS and PHP. Hacking with RaspberryPI and Arduino.'
url:                 http://moiseevigor.github.io
baseurl:             '/'
paginate:            5
# http://jekyllrb.com/docs/variables/
lsi: 			     true

# About/contact
author:
  name:              Igor Moiseev
  url:               https://twitter.com/moiseev_igor
  email:             moiseev.igor@gmail.com

# Custom vars
version:             1.0.0

# social
googleplus:			+IgorMoiseevAdventurer