# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
permalink:           pretty
# Use of `relative_permalinks` ensures post links from the index work properly.
relative_permalinks: true

# Setup
title:               Igor Moiseev
tagline:             'Applied mathematician, Web Developer'
description:         'Some notes about MySQL and PostgreSQL. Ceph''s Storage clustering and KVM virtualization. Programming with NodeJS and PHP. Hacking with RaspberryPI and Arduino.'
url:                 http://moiseevigor.github.io
baseurl:             ""
paginate:            5

github_repo_url:     https://github.com/moiseevigor/moiseevigor.github.io

disqus_shortname:    moiseevigor-github

webmention:
  username: moiseevigor.github.io

# About/contact
author:
  name:              Igor Moiseev
  url:               https://twitter.com/moiseev_igor
  email:             moiseev.igor@gmail.com

# Custom vars
version:             1.0.0

# social
googleplus:			     +IgorMoiseevAdventurer

# Gems
gems:
  - jekyll-sitemap
  - jekyll-mentions
#  - jekyll-time-to-read

# http://jekyllrb.com/docs/variables/
# https://github.com/jekyll/jekyll/issues/2516
lsi: true

exclude:
  - "*.json"
  - "*.log"
  - "bower_components"
  - "Gemfile*"
  - "LICENSE"
  - "node_modules"
  - "vendor"

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]