defaults: &defaults
  working_directory: ~/repo
version: 2
jobs:
  build:
    <<: *defaults
    docker:
      - image: cimg/ruby:3.1.1
    environment:
      BUNDLE_PATH: ~/repo/vendor/bundle
    steps:
      - run:
          name: Checkout code via HTTPS
          command: |
            git clone https://github.com/moiseevigor/moiseevigor.github.io.git .
            git checkout $CIRCLE_SHA1
      - restore_cache:
          keys:
            - rubygems-v2-{{ checksum "Gemfile.lock" }}
            - rubygems-v2-fallback
      - run:
          name: Bundle Install
          command: bundle check || bundle install
      - save_cache:
          key: rubygems-v2-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: Jekyll build
          command: bundle exec jekyll build
      - run:
          name: HTMLProofer tests
          command: |
            bundle exec htmlproofer ./_site \
              --only-4xx \
              --ignore_urls "/example.com/,/ws-na.amazon-adsystem.com/,/molpharm.aspetjournals.org/" \
              --ignore-status-codes "403"
      - persist_to_workspace:
          root: ./
          paths:
            - _site
workflows:
  version: 2
  test-deploy:
    jobs:
      - build
