name = "FDFormal"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["FDFormal"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
relaxedAutoImplicit = false
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.32.0"

[[lean_lib]]
name = "FDFormal"
