---
layout: post
title:  "Understanding /proc file system utilities"
description: ""
# date:   2015-02-01 18:05:45
categories:
- programming
tags:
- ubuntu
- linux
comments: true
---

/proc file system utilities

This package provides command line and full screen utilities for browsing procfs, a "pseudo" file system dynamically generated by the kernel to provide information about the status of entries in its process table (such as whether the process is running, stopped, or a "zombie").
It contains free, kill, pkill, pgrep, pmap, ps, pwdx, skill, slabtop, snice, sysctl, tload, top, uptime, vmstat, w, and watch.
